export default data = [
  {
    id: 1,
    name: "Eye Lashes",
    brand: 'Some (Pvt.) Ltd',
    soldBy: 'Store Name',
    category: 'Beauty',
    image: "https://www.shutterstock.com/image-vector/black-false-eyelashes-mascara-single-600w-791510866.jpg",
    price: "5.2$",
    desc: "Lorem Ipsum ....",
    likes: 10,
    sold: 20,
    inStock: 10,
    ratings: 2.5/5,
    reviews: 10,
    reviews: ["Nice", "Good"],
  },
  {
    id: 2,
    name: "Rice Flour",
    brand: 'Some (Pvt.) Ltd',
    soldBy: 'Store Name',
    category: 'Groceries',
    image: "https://healthiersteps.com/wp-content/uploads/2021/03/brown-rice-flour-bowl.jpg",
    price: "1.0$",
    desc: "Lorem Ipsum ....",
    likes: 10,
    sold: 25,
    inStock: 100,
    ratings: 2.5/5,
    reviews: 2,
    reviews: ["Nice", "Good"],
  },
  {
    id: 3,
    name: "Louis Watch",
    brand: 'LouisWill',
    soldBy: 'LouisWill',
    category: 'Watches, Glasses And Jewellery',
    image: "https://assorted.downloads.oppo.com/static/assets/products/oppo-watch-1/images/1920/convenience/sec1-cimg1-3ec5d106e1b4e26d9361b56dfd1f936b.png",
    price: "6.5$",
    desc: "Lorem Ipsum ....",
    likes: 5,
    sold: 10,
    inStock: 20,
    ratings: 4.5/5,
    reviews: 2,
    reviews: ["Nice", "Good"],
  },
  {
    id: 4,
    name: "AXOTIC USB",
    brand: 'AXOTIC',
    soldBy: 'AXOTIC',
    category: 'Computer & Laptops',
    image: "https://www.shophive.com/media/catalog/product/cache/3617b85921733ef3774cdbec091e1c0f/6/1/61ybyuo4ivl._ac_sl1200_.jpg",
    price: "7.2$",
    desc: "Lorem Ipsum ....",
    likes: 1,
    sold: 2,
    inStock: 5,
    ratings: 4.0/5,
    reviews: 2,
    reviews: ["Nice", "Good"],
  }
];
